name: CI
on:
  push:
    branches: [main]
    paths:
      - cli/src/**
      - cli/tsconfig.json
      - core/src/**
      - core/tsconfig.json
      - webapp/**
      - .prettier*
      - pnpm-lock.yaml
      - tsconfig.json
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: write
    with:
      semver-bump: prerelease
    secrets: inherit
