name: GitHub Release
run-name: Create ${{ inputs.tag }} GH release
on:
  workflow_call:
    inputs:
      package_label:
        type: string
        required: true
      package_name:
        type: string
        required: true
      prerelease:
        required: true
        type: string
      latest:
        required: true
        type: string
      tag:
        type: string
        required: true
      version:
        type: string
        required: true
      changelog:
        type: string
        required: true
jobs:
  create-gh-release:
    name: create github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: create github release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_NOTES=$(./.github/workflows/changelog_get.sh ${{ inputs.changelog }} ${{ inputs.version }})
          NPM_URL="https://www.npmjs.com/package/@eighty4/${{ inputs.package_name }}/v/${{ inputs.version }}"
          echo "[Published on npm]($NPM_URL)\r\n\r\n### Release notes\r\n\r\n$RELEASE_NOTES" > release_notes.md
          gh release create "${{ inputs.tag }}" \
            ${{ inputs.prerelease == 'true' && '--prerelease' || '' }} \
            ${{ inputs.latest == 'true' && '--latest' || '' }} \
            --notes-file release_notes.md \
            --title "${{ inputs.package_label }} v${{ inputs.version }}"
