name: Release
run-name: Create ${{ inputs.tag }} GH release
on:
  workflow_call:
    inputs:
      package_label:
        type: string
        required: true
      package_name:
        type: string
        required: true
      prerelease:
        required: true
        type: string
      latest:
        required: true
        type: string
      tag:
        type: string
        required: true
      version:
        type: string
        required: true
jobs:
  create-gh-release:
    name: create github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: create github release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          NPM_URL="https://www.npmjs.com/package/@eighty4/${{ inputs.package_name }}/v/${{ inputs.version }}"
          CREATED_RELEASE=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/eighty4/plunder/releases \
            -f tag_name="${{ inputs.tag }}" \
            -f name="${{ inputs.package_label }} v${{ inputs.version }}" \
            -f body="[Published to npm]($NPM_URL)" \
            -F draft=false \
            -F make_latest=${{ inputs.latest }} \
            -F prerelease=${{ inputs.prerelease }} \
            -F generate_release_notes=false)
