name: Verify
run-name: Verify ${{ github.ref }}
on:
  pull_request:
    branches: [ main ]
  push:
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test
      - run: echo 'With galleons and guns'
